apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # image: medicine-frontend:1.0
        image: 381491906666.dkr.ecr.us-east-1.amazonaws.com/medicine-frontend:multiarch
        ports:
          - containerPort: 80
        env: 
          - name: REACT_APP_BACKEND_URL
            value: "http://abd9f2caab1484b0e8b17d43813e5981-1061278927.us-east-1.elb.amazonaws.com/api"
