apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas:2
  selector:
    matchLabels:
    app: backend
  template:
    metadata:
      lables:
        app: backend
    spec:
      containers:
        - name: backend
          image: medicine-backend:1.0
          ports:
            - containerPort: 5001
          env:
            - name: SEC_KEY
              value: cE8z!$N#2sd@kR9wL5^yF
            - name: JWT_KEY
              value: "abc123!@#$%^&*()"
            - name: MONGODB_URI
              value: "mongodb+srv://hindupurv:monopoly2024@online-instrument-origi.qg8wzeg.mongodb.net/?retryWrites=true&w=majority&appName=online-instrument-original"